version: '3.8'

services:
  php:
    container_name: php
    entrypoint:  ["tail", "-f", "/dev/null"]
    build: ./
    volumes:
      - ./book_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
